name: cygwin

on:
 push:
   # since master is a symbolic reference to main, don't run for both
   branches-ignore:
     - 'master'
   tags:
     - '*'

jobs:
  ubuntu-build:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04
          - ubuntu-24.04-arm
          - ubuntu-26.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            dblatex \
            docbook2x \
            docbook-xsl \
            gawk \
            patch \
            python3-lxml \
            python3-ply \
            xmlto
      - run: |
          PLATFORM=pc-cygwin ./build.sh
